spring:
  profiles:
    include: common
  application:
    name: spring-cloud-gateway

server:
  port: 80

eureka: 
  client:       
    registerWithEureka: true   
    fetchRegistry: true
    service-url: 
      defaultZone: http://nodeA:10001/eureka/,http://nodeB:10002/eureka/