spring:  profiles:    include: common  application:    name: eureka-nodeA
server:
  port: 10001

eureka:  instance:
    hostname: nodeA
  client:    service-url:      defaultZone: http://nodeB:10002/eureka/