spring:
  profiles:
    include: common
  application:
    name: demo-eureka-nodeB

server:
  port: 10002

eureka:  instance:
    hostname: nodeB
  client:    service-url:      defaultZone: http://nodeA:10001/eureka/