spring:
  application:
    name: demo_eureka_nodeB
  profiles:
    include: common

server:
  port: 10002

eureka:  instance:
    hostname: nodeB
  client:    service-url:      defaultZone: http://nodeA:10001/eureka/