spring:
  application:
    name: demo-eureka-nodeA
  profiles:
    include: common

server:
  port: 10002

eureka:
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 4000 #清理无效节点的时间间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: nodeB
  client:
    service-url:
      defaultZone: http://nodeA:10001/eureka/
