smart:  data-machine-id: 1  swagger: true  enable-validator: true  enable-async: true  enable-feign-aop: true  enable-log-aop: trueserver:  port: 20021  spring:
  application:
    name: demoMallProductService