com:  liyulin:    data-machine-id: 1    swagger: true    validator: true    
spring:
  application:
    name: demo-mall-product-service
  profiles:
    include: 
      - common
      - common-db
      - eureka
      - product-db
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_product?${spring.datasource.url-common-paramters}
    username: root
    password: 123456

server:
  port: 20021