com:  liyulin:    data-machine-id: 1    swagger: true    validator: trueserver:  port: 20021  spring:
  application:
    name: demo-mall-product-service
  profiles:
    include: 
      - common
      - db-product
      - eureka