smart:
  datasources:
    product:
      url: jdbc:mysql://127.0.0.1:3306/demo_product
      username: ENC(PbMw+RtvRPYAo4Acbuxe4Q==)
      password: ENC(IwbzHJPe93Wevq8LVx0AwQ==)
      type-aliases-package: com.liyulin.demo.mall.product.entity
      mapper-interface-location: com.liyulin.demo.mall.product.mapper
      transaction-base-packages: com.liyulin.demo.mall.product.service
      mapper-xml-location: classpath*:/com/liyulin/demo/mall/product/mybatis/**/*.xml
