smart:
  dataMachineId: 1
  async: true
  api:
    validator: true
  aspect:
    repeatSubmitCheck: true
    rpclog: true
    rpcSecurity: true
    apilog: true
    apiSecurity: true
    
server:
  port: 20031
  
spring:
  application:
    name: demoMallUserService
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    timeout: 10000ms
    jedis:
      pool:
        max-active: 1000
        min-idle: 0
        max-idle: 100
        max-wait: 10000ms