smart:  data-machine-id: 2  swagger: true  enable-validator: true  enable-async: true  enable-feign-aop: true  enable-log-aop: trueserver:  port: 30001  spring:
  application:
    name: demo-merge-mall