smart:  dataMachineId: 2  async: true  api:    validator: true    repeatSubmitCheck: true  aspect:    rpclog: true    apilog: trueserver:  port: 30001  spring:
  application:
    name: demo-merge-mall