logging:
  config: classpath:log4j2.xml
  
server:
  servlet:
    context-path: /  compression:    enabled: true
  undertow:    direct-buffers: true
# 监控跟踪
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'