com:
  liyulin:
    data-machine-id: 1
  
spring:
  application:
    name: demo_mall_order_service
  profiles:
    include: 
      - common
      - common-db
      - eureka
      - order-db
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_order?${spring.datasource.url-common-paramters}
    username: root
    password: 123456

server:
  port: 20011