smart:
  dataMachineId: 1
  swagger: true
  validator: true
  async: true
  rpcLogAop: true
  apiLogAop: true

server:
  port: 20011
  
spring:
  application:
    name: demoMallOrderService