smart:
  datasources:
    order:
      url: jdbc:mysql://127.0.0.1:3306/demo_order
      username: ENC(SunrLNI7Betj34EBf2K++w==)
      password: ENC(pq4lrpcDa4xcumTaw5Y/2A==)
      type-aliases-package: com.liyulin.demo.mall.order.entity
      mapper-interface-location: com.liyulin.demo.mall.order.mapper
      transaction-base-packages: com.liyulin.demo.mall.order.service
      mapper-xml-location: classpath*:com/liyulin/demo/mall/order/mybatis/**.xml
      
jasypt:
  encryptor:
    password: 9CRjFqUi5Xw15rP0ecrV8A==