com:
  liyulin:
    data-machine-id: 1
    swagger: true
    validator: true

server:
  port: 20011
  
spring:
  application:
    name: demoMallOrderService
  profiles:
    include: 
      - common
      - db-order
      - eureka