spring:
  profiles:
    include: common
  application:
    name: demo-product-service

server:
  port: 20021

eureka: 
  client:       
    registerWithEureka: true   
    fetchRegistry: true
    service-url: 
      defaultZone: http://nodeA:10001/eureka/,http://nodeB:10002/eureka/