spring:
  profiles:
    include: common
  application:
    name: spring-boot-admin

server:
  port: 10011

eureka: 
  client:       
    registerWithEureka: true   
    fetchRegistry: true
    service-url: 
      defaultZone: http://nodeA:10001/eureka/,http://nodeB:10002/eureka/